# https://gist.github.com/UsamaAshraf/009e92d69ed0ef6dba66e534ca3d7bdc
version: "3.2"

services:
  rabbitmq-server:
    container_name: 'rabbitmq-server'
    image: rabbitmq:3-management
    networks:
      my_network:
        ipv4_address: 172.20.0.2
    ports:
    - "15672:15672"

  nfvo-api:
    container_name: 'nfvo'
    # build: ./python-service
    build: ./nfvo
    networks:
      my_network:
        ipv4_address: 172.20.0.3
    # 'rabbitmq-server' will be available as a network reference inside this service
    # and this service will start only after the RabbitMQ service does.
    depends_on:
      - rabbitmq-server
    # Keep it running.
    tty: true
    ports:
      - "8000:8000"
    volumes:
#      - './media:/media'
      - media:/media

  rabbitmq-consumer:
    container_name: 'rabbitmq-consumer'
    build: ./rabbitmq-consumer
    networks:
      my_network:
        ipv4_address: 172.20.0.4
    depends_on:
    - rabbitmq-server
    volumes:
      - media:/media


networks:
  my_network:
    ipam:
      config:
        - subnet: 172.20.0.0/24


# Host volumes used to store code.
volumes:
  media:
